apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-protobuf
spec:
  selector:
    matchLabels:
      app: testing-protobuf
  template:
    metadata:
      labels:
        app: testing-protobuf
    spec:
      containers:
        - name: testing-protobuf
          image: bhuvidh/testing-protobuf:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: testing-protobuf
  labels:
    provider: my-app
spec:
  type: LoadBalancer
  selector:
    app: testing-protobuf
  ports:
    - name: testing-protobuf
      port: 3000
      targetPort: 3000